# Generated by Django 3.2 on 2021-05-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20210528_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='due',
            field=models.DateTimeField(),
        ),
    ]
