# Generated by Django 3.2 on 2021-05-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_alter_work_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='due',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
