# Generated by Django 3.2 on 2021-05-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_alter_work_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='due',
            field=models.DateTimeField(blank=True),
        ),
    ]
